Create caroussel-promotion.html
Emimint/CinePro pull request #48
Opened 2024-03-24 23:43 UTC by Doupmat

2024-03-25 14:17 UTC, Emimint requested changes
On both the large and small screens the buttons are way too large : 

### On mobile : 

![image](https://github.com/Emimint/CinePro/assets/90863470/e2a4a9d8-9237-492b-89e3-4f234c0380c6)


### On desktop : 

![image](https://github.com/Emimint/CinePro/assets/90863470/51cfaf83-2367-4188-8f5c-e567bb22f72f)

How about making the entire image clickeable and remove the button?

2024-03-31 14:47 UTC, Emimint requested changes
@Doupmat please try this : 

```
    <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button
          type="button"
          data-bs-target="#myCarousel"
          data-bs-slide-to="0"
          class="active"
          aria-current="true"
          aria-label="Slide 1"
        ></button>
        <button
          type="button"
          data-bs-target="#myCarousel"
          data-bs-slide-to="1"
          aria-label="Slide 2"
        ></button>
        <button
          type="button"
          data-bs-target="#myCarousel"
          data-bs-slide-to="2"
          aria-label="Slide 3"
        ></button>
      </div>
      <div class="carousel-inner">
        <a href="https://www.google.com" target="_blank"
          ><div class="carousel-item active">
            <svg
              class="bd-placeholder-img"
              width="100%"
              height="100%"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
              preserveAspectRatio="xMidYMid slice"
              focusable="false"
            >
              <rect
                width="100%"
                height="100%"
                fill="var(--bs-secondary-color)"
              />
            </svg>
            <div class="container">
              <div class="carousel-caption text-start">
                <h1>Promo popcorn.</h1>
                <p>Obtenez 20% de rabais sur votre prochaine commande.</p>
              </div>
            </div>
          </div></a
        >
        <a href="https://www.google.com" target="_blank">
          <div class="carousel-item">
            <svg
              class="bd-placeholder-img"
              width="100%"
              height="100%"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
              preserveAspectRatio="xMidYMid slice"
              focusable="false"
            >
              <rect
                width="100%"
                height="100%"
                fill="var(--bs-secondary-color)"
              />
            </svg>
            <div class="container">
              <div class="carousel-caption">
                <h1>Deux hotdogs pour le prix d'un.</h1>
                <p>Promo Code: 1234A.</p>
              </div>
            </div>
          </div></a
        >
        <a href="https://www.google.com" target="_blank">
          <div class="carousel-item">
            <svg
              class="bd-placeholder-img"
              width="100%"
              height="100%"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
              preserveAspectRatio="xMidYMid slice"
              focusable="false"
            >
              <rect
                width="100%"
                height="100%"
                fill="var(--bs-secondary-color)"
              />
            </svg>
            <div class="container">
              <div class="carousel-caption text-end">
                <h1>Un billet gratuit a l'achat de deux billets.</h1>
                <p>Promo Code: AS120.</p>
              </div>
            </div>
          </div></a
        >
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#myCarousel"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#myCarousel"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
```

2024-04-01 18:07 UTC, cylia93 approved these changes

2024-04-01 18:07 UTC, Emimint approved these changes

2024-04-01 18:09 UTC, merged