Create movies-caroussel.html
Emimint/CinePro pull request #49
Opened 2024-03-25 00:38 UTC by Doupmat

2024-03-25 14:13 UTC, Emimint requested changes
Just a few things:

- I don't think we should embed videos there, we should **probably** stick to just images: all the videos right now can at the same time and on mobile I cannot seem to stop them individually. 
- On mobile, the "Achetez vos billets" button is way to big, maybe had a Bootstrap media querie to make it small on mobile view-ports

![image](https://github.com/Emimint/CinePro/assets/90863470/e09e4c26-a75b-4762-abd3-940e78fa8a30)

2024-03-30 19:12 UTC, Emimint approved these changes

2024-03-31 14:38 UTC, Emimint approved these changes
Neat 👍

2024-04-01 18:05 UTC, cylia93 approved these changes

2024-04-01 18:05 UTC, merged