21 create adminmovie agent dashboard co
Emimint/CinePro pull request #55
Opened 2024-03-31 02:20 UTC by cylia93

![dashbord](https://github.com/Emimint/CinePro/assets/141869795/a10896e4-e833-4679-9ea1-f95853036aa2)

2024-03-31 14:25 UTC, Emimint requested changes
@cylia93 la version mobile marche pas et le `settings.json` ne devrait pas faire parti des commits. 

![image](https://github.com/Emimint/CinePro/assets/90863470/09d94248-bf93-460e-ade7-04328492df2a)

2024-03-31 14:25 UTC, Emimint commented on .vscode/settings.json
Please add to `.gitignore` file

2024-03-31 14:25 UTC, Emimint commented on admin-agent-movie.html
Mobile version not working : 

![image](https://github.com/Emimint/CinePro/assets/90863470/73607538-25b2-4360-862d-22aaa1b72796)

2024-04-01 23:13 UTC, Emimint commented
@cylia93 @Doupmat  till need to be fixed later, but we can do that when we do the final layout : 


iPhone :

![image](https://github.com/Emimint/CinePro/assets/90863470/2acc485f-2cc1-4f0e-b9ce-101d8bd8addb)

sidebar, iPhone : 

![image](https://github.com/Emimint/CinePro/assets/90863470/aed956f9-4e0e-4dc3-a375-1d2e646c18b5)

2024-04-01 23:24 UTC, Emimint approved these changes

2024-04-02 20:50 UTC, Doupmat approved these changes
bon

2024-04-02 20:50 UTC, merged